### ISSUE TITLE
Cannot run `put` as first step

### ISSUE THREAD

**Issue by drnic** [starkandwayne/slack-notification-resource-boshrelease#1]
The `cd $1` fails if its the first step. Not sure why; but it does.

**Comment by robdimsdale** [comment]
+1 - I just ran into this.

I opened https://github.com/concourse/concourse/issues/82 as it looks like concourse should support this but doesn't

**Comment by drnic** [comment]
Sorry reading tickets in wrong order - I think it's the cd $1 but not sure what to do about it

**Comment by robdimsdale** [comment]
Others are running into this issue. @xoebus isn't sure where this bug is, but he's on the case.
