### ISSUE TITLE
Latest bosh final release does not use the updated job name

### ISSUE THREAD

**Issue by danger-ranger** [starkandwayne/slack-notification-resource-boshrelease#10]
The README says to use the template name: `slack-notification-resource` but found the v7 final release required the template name to be `just_install_packages`.

**Comment by RochesterinNYC** [comment]
We just came across this issue as well. As of right now, the template configuration line should be:

```
      - {release: slack-notification-resource, name: just_install_packages}
```

**Comment by LinuxBozo** [comment]
The README appropriate to the v7 version still references `just_install_packages` for what it's worth..
https://github.com/starkandwayne/slack-notification-resource-boshrelease/blob/v7/README.md

**Comment by jhunt** [comment]
This should all be cleared up with the v8 release, available now from bosh.io:

http://bosh.io/releases/github.com/cloudfoundry-community/slack-notification-resource-boshrelease?all=1
