### ISSUE TITLE
publish docker image

### ISSUE THREAD

**Issue by geoHeil** [starkandwayne/slack-notification-resource-boshrelease#11]
Current versions of concourse CI allow new resource types to be integrated automatically if a docker image is published. No change of the deployment is needed.

Please publish such a container/image to ease the integration of slack-notification resource.
See here for details: http://concourse.ci/configuring-resource-types.html
Thank you very much.

**Comment by cnelson** [comment]
The image for this resource type exists in thein the [cfcommunity repo](https://hub.docker.com/r/cfcommunity/slack-notification-resource/).
