### ISSUE TITLE
New Release pls.

### ISSUE THREAD

**Issue by muthu-aa** [starkandwayne/slack-notification-resource-boshrelease#13]
looks like the latest bosh release is several bug fixes and features behind from the upstream resource. can you pls. create a new release. 
https://github.com/cloudfoundry-community/slack-notification-resource

**Comment by drnic** [comment]
We’ve stopped supporting the boshrelease since concourse added resource_types. Are you ok with moving to resource_types in your concourse pipelines?

________________________________

**Comment by muthu-aa** [comment]
I have reconfigured pipeline to use resource_type and removed the bosh release. It just works, thank you.
