### ISSUE TITLE
support for not leaking the webhook URL

### ISSUE THREAD

**Issue by robdimsdale** [starkandwayne/slack-notification-resource-boshrelease#3]
When we post to the slack webhook, we post with `curl -v` which will leak the webhook.

This prevents this resource from being useful in publically-viewable pipelines.

How do you feel about a `params.silent` option, which will result in `curl -s` instead of `curl -v`, defaulting to `-v` if the param isn't set.

Happy to submit the PR for this if you want it

**Comment by robdimsdale** [comment]
see https://github.com/cloudfoundry-community/slack-notification-resource/pull/1

**Comment by robdimsdale** [comment]
I see the upstream PR got merged but I don't yet see a new final release.

When i go to the concourse at https://ci.starkandwayne.com/ I don't see a pipeline for this release. Am I missing something?

Is this bosh release no longer maintained?

**Comment by robdimsdale** [comment]
@drnic are you maintaining this repo, and if not can you point me to who is? I'd love to get my change in the upstream repo bumped.

If nobody is maintaining this I would be very happy taking ownership and resuming the CI so that bosh releases are built from the upstream resource.

**Comment by drnic** [comment]
Sorry I didn't appear to be Watching the repo after I moved it into the org. Thanks for bump.

**Comment by drnic** [comment]
Happy to hand over/share maintainership. There are many community resources to share around!

**Comment by robdimsdale** [comment]
ok thanks, and are you going to add a pipeline for this to automatically build the bosh release from the upstream repo? If so, which repo are you choosing? The current `pipeline.yml` suggests you're building from the fork at https://github.com/cloudfoundry-community/slack-notification-resource

**Comment by drnic** [comment]
Ok, back in the day we didn't have concourse db on RDS and so we lots concourse regularly because its on bosh-lite. Now we don't have this issue (using RDS) but slack concourse resource didn't get added back.

Added back and its running https://ci.starkandwayne.com/pipelines/slack-notification-resource-boshrelease/jobs/resource-image/builds/1

**Comment by robdimsdale** [comment]
Thanks very much - I'll close this issue. Just before I do that, are you aware that issues are turned off on the https://github.com/cloudfoundry-community/slack-notification-resource fork?

**Comment by drnic** [comment]
Thanks, fixed. I didn't mean to maintain a fork - at the time the upstream wasn't merging stuff asap. Sorry. And I wanted to package into bosh release. We can always move to @Nopik's parent repo in future.

**Comment by robdimsdale** [comment]
Great thanks. I appreciate it.

**Comment by drnic** [comment]
v4 now released
