### ISSUE TITLE
No v5 tag

### ISSUE THREAD

**Issue by robdimsdale** [starkandwayne/slack-notification-resource-boshrelease#4]
I see that v5 exists, but that there's no tag (or corresponding github release)

**Comment by mariash** [comment]
No v7 tag. Using release as github-release resource only pulls down v3.

Thanks

**Comment by drnic** [comment]
:sadpanda:

@longnguyen11288 can you please add the missing tags?

**Comment by drnic** [comment]
v7 release/tag created
